apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # echo -n 'root-pass' | base64 (see chart-values-minikube.yaml)
  db_root_pass: cm9vdC1wYXNz
  # echo -n 'my-app-db' | base64
  db_name: bXktYXBwLWRi
  # echo -n 'my-user' | base64
  db_user: bXktdXNlcg==
  # echo -n 'my-pass' | base64
  db_pass: bXktcGFzcw==