apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-mysql-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: java-mysql-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-mysql-app-service
            port:
              number: 8080